name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf-origin https://huggingface-cli:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/AteetVatan/masx-openchat-llm
          git push --force hf-origin HEAD:main
