name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for force-push to work
          lfs: true       # if you use Git LFS for model files

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Hugging Face Space via HTTPS
        run: |
          git remote add hf-origin https://huggingface.co/spaces/AteetVatan/masx-openchat-llm
          git push --force https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/AteetVatan/masx-openchat-llm HEAD:main
