name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:  # optional manual trigger

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # needed for force pushes
          lfs: true            # handles large files via Git LFS

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://$HF_TOKEN@huggingface.co/spaces/AteetVatan/masx-openchat-llm
          git push --force space main
